#!/bin/bash
# Markola one-shot setup — clone repo + run this script + you have local meeting notes.
#
# What this script does:
#   1. Installs Homebrew dependencies (whisper-cpp, ffmpeg, switchaudio-osx,
#      blackhole-2ch, background-music)
#   2. Downloads the Whisper medium model (~1.5 GB) for local transcription
#   3. Creates data + meetings dirs (respects $OBSIDIAN_MEETINGS_DIR env var)
#   4. Installs an env-sourcing wrapper at ~/.local/bin/markola
#   5. Verifies the toolchain end-to-end
#
# After this script: open the BackgroundMusic menu-bar app and set its
# Output Device to your physical speakers/headphones (it auto-follows
# changes when you swap AirPods etc.). Then `markola start`.
set -euo pipefail

echo "═══════════════════════════════════════════════════════════"
echo "  Markola Setup"
echo "═══════════════════════════════════════════════════════════"
echo ""

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WHISPER_MODELS_DIR="$HOME/.local/share/whisper-cpp/models"

# ─── Step 1: Homebrew dependencies ─────────────────────────────────
echo "── Step 1: Homebrew dependencies ──"

if ! command -v brew >/dev/null 2>&1; then
    echo "  ✗ Homebrew not installed. Install from https://brew.sh first."
    exit 1
fi

install_if_missing() {
    local formula="$1" check_cmd="${2:-$1}"
    if command -v "$check_cmd" >/dev/null 2>&1; then
        echo "  ✓ $formula"
    else
        echo "  → installing $formula"
        brew install "$formula"
    fi
}

install_cask_if_missing() {
    local cask="$1" check_path="${2:-/Applications/$1.app}"
    if [[ -e "$check_path" ]] || brew list --cask "$cask" >/dev/null 2>&1; then
        echo "  ✓ $cask (cask)"
    else
        echo "  → installing $cask (may prompt for password — audio drivers need sudo)"
        brew install --cask "$cask"
    fi
}

install_if_missing "whisper-cpp" "whisper-cli"
install_if_missing "ffmpeg" "ffmpeg"
install_if_missing "switchaudio-osx" "SwitchAudioSource"
install_cask_if_missing "blackhole-2ch" "/Library/Audio/Plug-Ins/HAL/BlackHole2ch.driver"
install_cask_if_missing "background-music" "/Applications/Background Music.app"

echo ""

# ─── Step 2: Whisper model ─────────────────────────────────────────
echo "── Step 2: Whisper model (ggml-medium.bin, ~1.5 GB) ──"
mkdir -p "$WHISPER_MODELS_DIR"
if [[ -f "$WHISPER_MODELS_DIR/ggml-medium.bin" ]]; then
    echo "  ✓ medium model already downloaded"
else
    echo "  → downloading…"
    curl -L --progress-bar \
        "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.bin" \
        -o "$WHISPER_MODELS_DIR/ggml-medium.bin"
    echo "  ✓ downloaded"
fi
echo ""

# ─── Step 3: Data + meetings directories ───────────────────────────
echo "── Step 3: Data + meetings directories ──"
mkdir -p "$HOME/.local/share/markola"/{recordings,logs}
# Honor env override; default to ~/Documents/markola (NOT Obsidian/Intercom — generic)
MEETINGS_DIR="${OBSIDIAN_MEETINGS_DIR:-$HOME/Documents/markola}"
mkdir -p "$MEETINGS_DIR"
echo "  ✓ data dir:     $HOME/.local/share/markola"
echo "  ✓ meetings dir: $MEETINGS_DIR"
echo "  (override via OBSIDIAN_MEETINGS_DIR env var)"
echo ""

# ─── Step 4: Wrapper script (sources env) ──────────────────────────
echo "── Step 4: CLI wrapper at ~/.local/bin/markola ──"
LOCAL_BIN="$HOME/.local/bin"
mkdir -p "$LOCAL_BIN"

cat > "$LOCAL_BIN/markola" << EOF
#!/bin/bash
# Markola wrapper — sources user env (OBSIDIAN_MEETINGS_DIR, BLACKHOLE_DEVICE
# overrides etc.) before invoking the actual script. Generated by setup.sh.
[ -f "\$HOME/.ai-tools/config.env" ]       && source "\$HOME/.ai-tools/config.env"       2>/dev/null
[ -f "\$HOME/.ai-tools/config.env.local" ] && source "\$HOME/.ai-tools/config.env.local" 2>/dev/null
exec "$SCRIPT_DIR/markola.sh" "\$@"
EOF
chmod +x "$LOCAL_BIN/markola"
chmod +x "$SCRIPT_DIR/markola.sh"
find "$SCRIPT_DIR" -name "*.sh" -exec chmod +x {} \;
echo "  ✓ wrapper installed at $LOCAL_BIN/markola"

if ! echo "$PATH" | tr ':' '\n' | grep -q "^$LOCAL_BIN$"; then
    echo "  ⚠ $LOCAL_BIN is NOT in your PATH"
    echo "    Add to ~/.zshrc or ~/.bash_profile:"
    echo "      export PATH=\"\$HOME/.local/bin:\$PATH\""
fi
echo ""

# ─── Step 5: Audio routing setup (BackgroundMusic preferred) ───────
echo "── Step 5: Audio routing ──"
echo "  Markola records system audio via a virtual capture device."
echo "  Recommended: use BackgroundMusic (just installed)."
echo ""
echo "  After this script finishes:"
echo "    1. Launch the 'Background Music' app (or it auto-launches at next login)"
echo "    2. System Settings → Sound → Output → set to 'Background Music'"
echo "    3. Click the BG Music menu-bar icon → Output Device → pick your"
echo "       physical speakers / AirPods / headphones (you can change anytime)"
echo "    4. (Optional) Set BLACKHOLE_DEVICE='Background Music' in"
echo "       ~/.ai-tools/config.env.local (or wherever your env file is) so"
echo "       markola records from the BG Music capture stream."
echo ""
echo "  Alternative (static): use BlackHole 2ch with a Multi-Output Device"
echo "  named 'Markola Output' in Audio MIDI Setup. Less flexible because the"
echo "  Multi-Output Device can't auto-follow when you swap headphones."
echo ""

# ─── Step 6: Verify ────────────────────────────────────────────────
echo "── Step 6: Verify ──"
errors=0
check() {
    local label="$1" cmd="$2"
    if eval "$cmd" >/dev/null 2>&1; then
        echo "  ✓ $label"
    else
        echo "  ✗ $label"
        errors=$((errors + 1))
    fi
}

check "whisper-cli on PATH"      "command -v whisper-cli"
check "ffmpeg on PATH"           "command -v ffmpeg"
check "SwitchAudioSource"        "command -v SwitchAudioSource"
check "BlackHole driver loaded"  "SwitchAudioSource -a 2>/dev/null | grep -q 'BlackHole 2ch'"
check "BG Music driver loaded"   "SwitchAudioSource -a 2>/dev/null | grep -q 'Background Music'"
check "whisper model present"    "[ -f '$WHISPER_MODELS_DIR/ggml-medium.bin' ]"
check "markola wrapper"          "[ -x '$LOCAL_BIN/markola' ]"
check "claude CLI on PATH"       "command -v claude"

echo ""
if [[ $errors -eq 0 ]]; then
    echo "═══════════════════════════════════════════════════════════"
    echo "  ✓ Markola setup complete — all checks passed."
    echo "═══════════════════════════════════════════════════════════"
else
    echo "═══════════════════════════════════════════════════════════"
    echo "  ⚠ $errors check(s) failed. Re-run setup or fix manually."
    echo "═══════════════════════════════════════════════════════════"
fi

echo ""
echo "Next:"
echo "  1. Configure BackgroundMusic per Step 5 above"
echo "  2. markola start         — start meeting auto-detection daemon"
echo "  3. markola status        — verify it's running"
echo "  4. markola record 'test' — manual recording test"
echo "  5. markola process FILE  — process any audio/video file directly"
echo ""
echo "Notes save to: $MEETINGS_DIR/<platform>/YYYY-MM-DD_HHMMSS_title.md"
